"""LaTeX export helpers for thesis waterfall panel stacks."""

from __future__ import annotations

import os
import subprocess
from contextlib import nullcontext
from dataclasses import dataclass
from pathlib import Path

import matplotlib
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

from superconductivity.style.cpd4 import cmap as default_cmap
from superconductivity.utilities.types import LIM, NDArray64

from .heatmap import get_thesis_heatmap_matplotlib
from .surface import get_thesis_surface_matplotlib
from .waterfall import get_thesis_waterfall_matplotlib


@dataclass(frozen=True)
class StackedThesisExport:
    """Resolved output paths for a thesis waterfall stack export.

    Attributes
    ----------
    stem
        Output stem without a file suffix.
    pgf_dir
        Directory containing the exported wrapper asset.
    pdf_dir
        Directory containing the exported PDF assets and preview `.tex`.
    stacked_pgf
        Wrapper PGF file stacking the three panel PDFs.
    waterfall_pdf
        PDF export of the waterfall panel.
    surface_pdf
        PDF export of the surface panel.
    heatmap_pdf
        PDF export of the heatmap panel.
    preview_tex
        Standalone LaTeX file that inputs ``stacked_pgf``.
    preview_pdf
        Preview PDF generated by compiling ``preview_tex``.
    """

    stem: Path
    pgf_dir: Path
    pdf_dir: Path
    stacked_pgf: Path
    waterfall_pdf: Path
    surface_pdf: Path
    heatmap_pdf: Path
    preview_tex: Path
    preview_pdf: Path


def _normalize_stem(stem: str | Path) -> Path:
    """Normalize an output stem by stripping a file suffix if present.

    Parameters
    ----------
    stem
        Output name which may optionally already contain a suffix.

    Returns
    -------
    Path
        Normalized path fragment without a suffix.
    """
    path = Path(stem)
    return path.with_suffix("") if path.suffix else path


def _tagged_path(
    root: Path,
    stem: Path,
    *,
    tag: str,
    suffix: str,
) -> Path:
    """Build an output path from a root directory, stem, and tag.

    Parameters
    ----------
    root
        Base output directory.
    stem
        Relative figure stem without suffix.
    tag
        Tag appended to the stem.
    suffix
        Target file suffix including the leading dot.

    Returns
    -------
    Path
        Tagged output path under ``root``.
    """
    base = root / stem
    return base.with_name(f"{base.name}_{tag}").with_suffix(suffix)


def _build_export_paths(
    *,
    stem: str | Path,
    path_pgf: str | Path,
    path_pdf: str | Path | None,
) -> StackedThesisExport:
    """Resolve all filesystem paths used by the stack export.

    Parameters
    ----------
    stem
        Shared output stem for all generated assets.
    path_pgf
        Base directory receiving the wrapper PGF and shipped panel PDFs.
    path_pdf
        Base directory receiving the PDF previews and standalone `.tex`.

    Returns
    -------
    StackedThesisExport
        Dataclass containing all resolved output paths.
    """
    stem_path = _normalize_stem(stem)
    pgf_dir = Path(path_pgf).expanduser().resolve()
    pdf_dir = pgf_dir if path_pdf is None else Path(path_pdf).expanduser().resolve()
    return StackedThesisExport(
        stem=stem_path,
        pgf_dir=pgf_dir,
        pdf_dir=pdf_dir,
        stacked_pgf=_tagged_path(
            pgf_dir,
            stem_path,
            tag="stacked",
            suffix=".pgf",
        ),
        waterfall_pdf=_tagged_path(
            pdf_dir,
            stem_path,
            tag="waterfall",
            suffix=".pdf",
        ),
        surface_pdf=_tagged_path(
            pdf_dir,
            stem_path,
            tag="surface",
            suffix=".pdf",
        ),
        heatmap_pdf=_tagged_path(
            pdf_dir,
            stem_path,
            tag="heatmap",
            suffix=".pdf",
        ),
        preview_tex=_tagged_path(
            pdf_dir,
            stem_path,
            tag="stacked",
            suffix=".tex",
        ),
        preview_pdf=_tagged_path(
            pdf_dir,
            stem_path,
            tag="stacked",
            suffix=".pdf",
        ),
    )


def _stacked_panel_pdf_path(
    stacked_pgf: Path,
    *,
    tag: str,
) -> Path:
    """Return the shipped panel PDF path next to a stacked wrapper.

    Parameters
    ----------
    stacked_pgf
        Wrapper PGF path.
    tag
        Panel tag, for example ``"waterfall"``.

    Returns
    -------
    Path
        PDF path located next to ``stacked_pgf``.
    """
    base = stacked_pgf.stem.removesuffix("_stacked")
    return stacked_pgf.with_name(f"{base}_{tag}.pdf")


def _ensure_parent(path: Path) -> None:
    """Ensure the parent directory of a path exists.

    Parameters
    ----------
    path
        Path whose parent directory should be created.
    """
    path.parent.mkdir(parents=True, exist_ok=True)


def _save_figure_assets(
    fig: plt.Figure,
    *,
    pdf_path: Path,
) -> None:
    """Save one Matplotlib figure as PDF.

    Parameters
    ----------
    fig
        Figure to save.
    pdf_path
        Destination PDF file.
    """
    _ensure_parent(pdf_path)
    fig.savefig(
        pdf_path,
        format="pdf",
        transparent=True,
        facecolor="none",
        edgecolor="none",
    )


def _relative_posix_path(path: Path, start: Path) -> str:
    """Return a relative path formatted for LaTeX ``\\input``.

    Parameters
    ----------
    path
        Target file path.
    start
        Directory from which the relative path should be computed.

    Returns
    -------
    str
        Relative path using forward slashes.
    """
    return Path(os.path.relpath(path, start)).as_posix()


def build_stacked_wrapper_pgf(
    *,
    stacked_pgf: Path,
    waterfall_pdf: Path,
    surface_pdf: Path,
    heatmap_pdf: Path,
    stack_gap: str = "-0.8em",
) -> str:
    """Build a lightweight PGF wrapper that stacks panel PDFs.

    Parameters
    ----------
    stacked_pgf
        Wrapper PGF path. Panel PDFs are made relative to its parent
        directory.
    waterfall_pdf
        Path to the waterfall PDF.
    surface_pdf
        Path to the surface PDF.
    heatmap_pdf
        Path to the heatmap PDF.
    stack_gap
        LaTeX vertical gap inserted between neighboring panels.

    Returns
    -------
    str
        Wrapper PGF content that can be imported in a normal LaTeX figure.
    """
    waterfall_rel = _relative_posix_path(waterfall_pdf, stacked_pgf.parent)
    surface_rel = _relative_posix_path(surface_pdf, stacked_pgf.parent)
    heatmap_rel = _relative_posix_path(heatmap_pdf, stacked_pgf.parent)
    return "\n".join(
        [
            r"\begingroup",
            r"\centering",
            rf"\includegraphics[width=\linewidth]{{{waterfall_rel}}}\par",
            rf"\vspace{{{stack_gap}}}",
            rf"\includegraphics[width=\linewidth]{{{surface_rel}}}\par",
            rf"\vspace{{{stack_gap}}}",
            rf"\includegraphics[width=\linewidth]{{{heatmap_rel}}}\par",
            r"\endgroup",
            "",
        ]
    )


def build_preview_tex(
    *,
    waterfall_pdf: Path,
    surface_pdf: Path,
    heatmap_pdf: Path,
    preview_tex: Path,
    stack_gap: str = "-0.8em",
) -> str:
    """Build a standalone preview document from stacked panel PDFs.

    Parameters
    ----------
    waterfall_pdf
        PDF preview of the waterfall panel.
    surface_pdf
        PDF preview of the surface panel.
    heatmap_pdf
        PDF preview of the heatmap panel.
    preview_tex
        Standalone `.tex` path. The panel paths are made relative to its
        parent directory.
    stack_gap
        LaTeX vertical gap inserted between neighboring panels.

    Returns
    -------
    str
        Standalone LaTeX document content.
    """
    waterfall_rel = _relative_posix_path(waterfall_pdf, preview_tex.parent)
    surface_rel = _relative_posix_path(surface_pdf, preview_tex.parent)
    heatmap_rel = _relative_posix_path(heatmap_pdf, preview_tex.parent)
    return "\n".join(
        [
            r"\documentclass[varwidth,border=2pt]{standalone}",
            r"\usepackage[T1]{fontenc}",
            r"\usepackage[utf8]{inputenc}",
            r"\usepackage{graphicx}",
            r"\pagestyle{empty}",
            r"\begin{document}",
            r"\centering",
            rf"\includegraphics[width=\linewidth]{{{waterfall_rel}}}\par",
            rf"\vspace{{{stack_gap}}}",
            rf"\includegraphics[width=\linewidth]{{{surface_rel}}}\par",
            rf"\vspace{{{stack_gap}}}",
            rf"\includegraphics[width=\linewidth]{{{heatmap_rel}}}",
            r"\end{document}",
            "",
        ]
    )


def _resolve_latex_command(
    *,
    latex_command: str | None,
    pgf_texsystem: str | None,
) -> str:
    """Resolve the LaTeX engine used for preview compilation.

    Parameters
    ----------
    latex_command
        Explicit LaTeX command requested by the caller.
    pgf_texsystem
        Explicit Matplotlib PGF tex system requested by the caller.

    Returns
    -------
    str
        LaTeX engine name to use for compilation.
    """
    if latex_command is not None:
        return latex_command
    if pgf_texsystem is not None:
        return pgf_texsystem
    return str(matplotlib.rcParams["pgf.texsystem"])


def compile_thesis_preview(
    preview_tex: str | Path,
    *,
    latex_command: str | None = None,
) -> Path:
    """Compile a standalone thesis preview document into PDF.

    Parameters
    ----------
    preview_tex
        Standalone LaTeX file produced by ``build_preview_tex``.
    latex_command
        LaTeX command used for compilation. When omitted, the current
        Matplotlib ``pgf.texsystem`` setting is used.

    Returns
    -------
    Path
        Compiled preview PDF path.

    Raises
    ------
    RuntimeError
        If the LaTeX compiler is missing or returns a non-zero exit code.
    """
    tex_path = Path(preview_tex).expanduser().resolve()
    command_name = _resolve_latex_command(
        latex_command=latex_command,
        pgf_texsystem=None,
    )
    command = [
        command_name,
        "-interaction=nonstopmode",
        "-halt-on-error",
        tex_path.name,
    ]

    try:
        subprocess.run(
            command,
            cwd=tex_path.parent,
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as exc:
        raise RuntimeError(f"LaTeX command {command_name!r} was not found.") from exc
    except subprocess.CalledProcessError as exc:
        output = exc.stdout or exc.stderr or ""
        raise RuntimeError(
            "LaTeX preview compilation failed.\n" + output.strip()
        ) from exc

    return tex_path.with_suffix(".pdf")


def export_stacked_waterfall_thesis(
    x: NDArray64,
    y: NDArray64,
    z: NDArray64,
    *,
    stem: str | Path,
    path_pgf: str | Path,
    path_pdf: str | Path | None = None,
    xlim: LIM = None,
    ylim: LIM = None,
    zlim: LIM = None,
    clim: LIM = None,
    trace_step: int = 1,
    xlabel: str = "x",
    ylabel: str = "y",
    zlabel: str = "z",
    clabel: str | None = None,
    line_color: str = "black",
    line_width: float = 0.6,
    line_alpha: float = 1.0,
    surface_alpha: float = 1.0,
    heatmap_alpha: float = 1.0,
    heatmap_z_level: float = 0.0,
    cmap_mpl: ListedColormap = default_cmap(),
    elev: float = 20.0,
    azim: float = -70.0,
    figsize: tuple[float, float] = (6.2, 3.9),
    stack_gap: str = "-0.8em",
    compile_preview: bool = False,
    latex_command: str | None = None,
    pgf_texsystem: str | None = None,
) -> StackedThesisExport:
    """Export a three-panel waterfall stack for LaTeX-based composition.

    Parameters
    ----------
    x
        1D x-axis values of shape ``(Nx,)``.
    y
        1D sweep values of shape ``(Ny,)``.
    z
        2D measurement array of shape ``(Ny, Nx)`` with ``z[y_i, x_j]``.
    stem
        Shared output stem for all generated assets.
    path_pgf
        Directory receiving the wrapper PGF and shipped panel PDFs. The
        parameter keeps its historical name for compatibility.
    path_pdf
        Directory receiving the panel PDFs and the standalone preview `.tex`.
        When omitted, it falls back to ``path_pgf``.
    xlim, ylim, zlim
        Optional axis limits shared by the exported panels.
    clim
        Optional color limits for the surface and heatmap panels.
    trace_step
        Plot every ``trace_step``-th fixed-``y`` trace.
    xlabel, ylabel, zlabel
        Axis labels.
    clabel
        Optional colorbar label. Defaults to ``zlabel``.
    line_color
        Waterfall line color.
    line_width
        Waterfall line width.
    line_alpha
        Waterfall line opacity.
    surface_alpha
        Surface panel opacity.
    heatmap_alpha
        Heatmap panel opacity.
    heatmap_z_level
        Z position used for the flat heatmap plane.
    cmap_mpl
        Matplotlib colormap used for the surface and heatmap panels.
    elev
        Elevation angle passed to Matplotlib's 3D view.
    azim
        Azimuth angle passed to Matplotlib's 3D view.
    figsize
        Figure size shared by the three exported panels.
    stack_gap
        LaTeX vertical gap inserted between neighboring stacked panels in the
        wrapper PGF.
    compile_preview
        If ``True``, compile the generated standalone `.tex` into a preview
        PDF using ``latex_command``.
    latex_command
        LaTeX command used when ``compile_preview`` is enabled. When omitted,
        it defaults to ``pgf_texsystem`` or Matplotlib's current
        ``pgf.texsystem`` value.
    pgf_texsystem
        Optional LaTeX engine used as the default preview compiler.

    Returns
    -------
    StackedThesisExport
        Dataclass containing the resolved asset paths.
    """
    export = _build_export_paths(
        stem=stem,
        path_pgf=path_pgf,
        path_pdf=path_pdf,
    )
    shipped_waterfall_pdf = _stacked_panel_pdf_path(
        export.stacked_pgf,
        tag="waterfall",
    )
    shipped_surface_pdf = _stacked_panel_pdf_path(
        export.stacked_pgf,
        tag="surface",
    )
    shipped_heatmap_pdf = _stacked_panel_pdf_path(
        export.stacked_pgf,
        tag="heatmap",
    )
    command_name = _resolve_latex_command(
        latex_command=latex_command,
        pgf_texsystem=pgf_texsystem,
    )

    fig_waterfall, _ = get_thesis_waterfall_matplotlib(
        x=x,
        y=y,
        z=z,
        xlim=xlim,
        ylim=ylim,
        zlim=zlim,
        trace_step=trace_step,
        xlabel=xlabel,
        ylabel=ylabel,
        zlabel=zlabel,
        line_color=line_color,
        line_width=line_width,
        alpha=line_alpha,
        elev=elev,
        azim=azim,
        figsize=figsize,
    )
    fig_surface, _ = get_thesis_surface_matplotlib(
        x=x,
        y=y,
        z=z,
        xlim=xlim,
        ylim=ylim,
        zlim=zlim,
        clim=clim,
        trace_step=trace_step,
        xlabel=xlabel,
        ylabel=ylabel,
        zlabel=zlabel,
        clabel=clabel,
        surface_alpha=surface_alpha,
        cmap_mpl=cmap_mpl,
        show_colorbar=False,
        elev=elev,
        azim=azim,
        figsize=figsize,
    )
    fig_heatmap, _ = get_thesis_heatmap_matplotlib(
        x=x,
        y=y,
        z=z,
        xlim=xlim,
        ylim=ylim,
        clim=clim,
        trace_step=trace_step,
        xlabel=xlabel,
        ylabel=ylabel,
        zlabel=zlabel,
        clabel=clabel,
        z_level=heatmap_z_level,
        heatmap_alpha=heatmap_alpha,
        show_zaxis=False,
        cmap_mpl=cmap_mpl,
        show_colorbar=False,
        elev=elev,
        azim=azim,
        figsize=figsize,
    )

    try:
        rc_context = (
            matplotlib.rc_context({"pgf.texsystem": pgf_texsystem})
            if pgf_texsystem is not None
            else nullcontext()
        )
        with rc_context:
            _save_figure_assets(
                fig_waterfall,
                pdf_path=export.waterfall_pdf,
            )
            _save_figure_assets(
                fig_surface,
                pdf_path=export.surface_pdf,
            )
            _save_figure_assets(
                fig_heatmap,
                pdf_path=export.heatmap_pdf,
            )
            if export.waterfall_pdf != shipped_waterfall_pdf:
                _ensure_parent(shipped_waterfall_pdf)
                fig_waterfall.savefig(
                    shipped_waterfall_pdf,
                    format="pdf",
                    transparent=True,
                    facecolor="none",
                    edgecolor="none",
                )
            if export.surface_pdf != shipped_surface_pdf:
                _ensure_parent(shipped_surface_pdf)
                fig_surface.savefig(
                    shipped_surface_pdf,
                    format="pdf",
                    transparent=True,
                    facecolor="none",
                    edgecolor="none",
                )
            if export.heatmap_pdf != shipped_heatmap_pdf:
                _ensure_parent(shipped_heatmap_pdf)
                fig_heatmap.savefig(
                    shipped_heatmap_pdf,
                    format="pdf",
                    transparent=True,
                    facecolor="none",
                    edgecolor="none",
                )
    finally:
        plt.close(fig_waterfall)
        plt.close(fig_surface)
        plt.close(fig_heatmap)

    _ensure_parent(export.stacked_pgf)
    export.stacked_pgf.write_text(
        build_stacked_wrapper_pgf(
            stacked_pgf=export.stacked_pgf,
            waterfall_pdf=shipped_waterfall_pdf,
            surface_pdf=shipped_surface_pdf,
            heatmap_pdf=shipped_heatmap_pdf,
            stack_gap=stack_gap,
        ),
        encoding="utf-8",
    )

    _ensure_parent(export.preview_tex)
    export.preview_tex.write_text(
        build_preview_tex(
            waterfall_pdf=export.waterfall_pdf,
            surface_pdf=export.surface_pdf,
            heatmap_pdf=export.heatmap_pdf,
            preview_tex=export.preview_tex,
            stack_gap=stack_gap,
        ),
        encoding="utf-8",
    )

    if compile_preview:
        compile_thesis_preview(
            export.preview_tex,
            latex_command=command_name,
        )

    return export


__all__ = [
    "StackedThesisExport",
    "build_preview_tex",
    "build_stacked_wrapper_pgf",
    "compile_thesis_preview",
    "export_stacked_waterfall_thesis",
]
